GET http://localhost:3001/

###
POST https://fullstack-2828.fly.dev/api/persons HTTP/1.1
content-type: application/json

{  
    "name": "Seppo Talasmaa",
    "number": "040-1231231"
}
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{  
    "name": "Seppo Talasmaa",
    "number": "040-1231231"
}